---
title: "AFM_dash3"
author: "Mazama Science"
date: "3/15/2021"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(AirFireModeling)
library(shiny)
library(crosstalk)
library(lubridate)
library(leaflet)
library(gt)
library(MazamaSpatialUtils)

PWFSLSmoke::initializeMazamaSpatialUtils()
MazamaSpatialUtils::setSpatialDataDir("~/Data/Spatial")
setModelDataDir('~/Data/BlueSky')
```

```{r model_date_panel}

inputPanel(
    selectizeInput(
      "model", 
      label = "Model Name",
      choices = bluesky_modelInfo$modelName, 
      width = "100%"
    ), 
    dateInput(
      "date", 
      label = "Model Run Date", 
      max = today(), 
      width = "100%"
    ),
    fillCol(),
    uiOutput(
      "loadLink"
    )  
  )
```

```{r main_panel, message=FALSE}
leafletOutput(outputId = "map")

sliderInput(
  "index", 
  "Slice", 
  min = 1, 
  max = 4,
  value = 1, 
  step = 1, 
  width = "100%", 
  animate = TRUE
)


plotOutput("plot")

gt_output("table")
```

```{r backend}
bs <- eventReactive({ input$load }, {
  
  tryCatch(raster_load(
    modelName = input$model, 
    modelRun = strftime(input$date, "%Y%m%d00")
  ), error = function(err) { NULL })
  
})


coords <- reactive({ input$map_click })

observeEvent({  bs() }, {
  
  nz <- tryCatch(dim(bs()[[1]])[3], error = function(err) { "Error." })
  
  updateSliderInput(
    session,
    "index",
    max = nz,
    value = 1 
  )

})



observe({
  
  index <- as.numeric(input$index)

  layer <- bs()[[1]][[index]]

  name <- names(layer) 
  
    pal <- colorNumeric(c("#FFFFFF00", "#8F8172", "#675C58", "#2E2D2B", "#B19778", "#7D3540"), c(0, 0.1, 5, 10, 20, 40, 60), na.color = "transparent", alpha = TRUE)
  

    leafletProxy("map") %>%
    removeImage(layerId = "raster") %>% 
    addRasterImage(layer, layerId = "raster", colors = pal) 
    
})

observeEvent({ input$map_click }, {
  leafletProxy("map") %>% 
    clearMarkers() %>%
    addMarkers(coords()$lng, coords()$lat)
})



```


```{r outputs}

output$loadLink <- renderUI({
  
  req(input$model)
  actionButton(
    inputId = "load",
    label = tags$h4(paste("Load", input$model))
  ) 
  
})

output$map <- renderLeaflet({
  
 leaflet() %>%
  addTiles() 
  
})

output$plot <- renderPlot({
  
  req(bs(), coords())
  raster_spaghettiPlot(bs(), coords()$lng , coords()$lat)

})

# output$table <- render_gt({
#   req(bs(), coords())
#   df <- raster_toMonitor(bs()[[1]][[input$index]], coords()$lng, coords()$lat)
#   gt(df$data)
# })
```

