---
title: "Bluesky Inspector"
author: "Mazama Science"
date: "3/17/2021"
output: html_document
runtime: shiny
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(shiny)
library(lubridate)
library(MazamaSpatialUtils)
library(AirFireModeling)
library(AirFireWRF)
library(AirFirePlots)

PWFSLSmoke::initializeMazamaSpatialUtils()
MazamaSpatialUtils::setSpatialDataDir("~/Data/Spatial")
setModelDataDir('~/Data/BlueSky')
setWRFDataDir('~/Data/WRF')
```

```{css, echo = FALSE}

.btn {
  background-color: whitesmoke;
}

.btn#load {
  margin-top: 6%; 
}

.btn#opts_bt {
  margin-top: 12%;
}

#shiny-notification-panel {
  position:fixed;
  top: 1%;
}

```

```{js, echo = FALSE}

// Hide options by default
$('#opts_menu').parent().hide()

// Options toggle
$('#opts_bt').on('click', () => {
  $('#opts_menu').parent().toggle()
})

```


```{r model_date_panel}

# Begin UI def
inputPanel(
    selectizeInput(
      "model", 
      label = "Model Name",
      choices = c(
      "PNW-1.33km",
      "PNW-4km",
      "CANSAC-1.33km",
      "CANSAC-4km"
      ), 
      selected = "PNW-4km"
    ), 
    dateInput(
      "date", 
      label = "Model Run Date", 
      max = today()
    ), 
    actionButton(
      "opts_bt", 
      "", 
      icon = icon("cog")
    ), 
    uiOutput("loadLink"),
    id = "main"
  )

inputPanel(
  checkboxGroupInput(
    "plt_opts", 
    "Plot Options",
    choices = c(
      "State Boundaries", 
      "County Boundaries",
      "Scalar Field", 
      "Vector Field"
    ), 
    selected = c(
      "State Boundaries", 
      "Scalar Field", 
      "Vector Field"
    )
  ),
  selectizeInput(
    "index", 
    "Bluesky Slice", 
    choices = ""
    ),
  selectizeInput(
    "z_wrf",
    "WRF Slice", 
    choices = 1:72, 
    selected = 8
  ), 
  id = "opts_menu"
)

tags$hr()

plotOutput("plot", width = "100%", height = "800px", click = "plot_click")

actionButton(
  "prv", 
  "",
  icon = icon("arrow-circle-left")
)

actionButton(
  "fwd", 
  "", 
  icon = icon("arrow-circle-right")
)

tags$hr()

plotOutput("subplot", width = "90%")


# # # End UI def
# # # Begin Logic

index <- eventReactive({ input$index }, { return(as.numeric(input$index)) })

options <- eventReactive({ input$plt_opts }, { return(input$plt_opts) })

meta <- eventReactive({ input$load }, {
  
  bluesky_modelInfo  %>% 
    dplyr::filter(.data$modelName == input$model)

})

bs <- eventReactive({ input$load }, {
  
  p <- Progress$new()
  p$set(message = "Loading Bluesky model...")
  on.exit(p$close())
  
  raster <- tryCatch(raster_load(
    modelName = input$model, 
    modelRun = strftime(input$date, "%Y%m%d00")
  ), error = function(err) { NULL })

  return(raster)
  
})

wrf <- eventReactive({ input$load; input$z_wrf }, {
  
  p <- Progress$new()
  p$set(message = "Loading WRF model...")
  on.exit(p$close())
  
  # WRF-only parameters
  modelRunHour <- input$z_wrf
  varNames <- c("U10", "V10")   #  Wind vector components
  res <- 0.1                    # Use res = 0.1 for state-sized regions
  
  xlim <- c(meta()[['MIN_LONGITUDE']], meta()[['MAX_LONGITUDE']])
  ylim <- c(meta()[['MIN_LATITUDE']], meta()[['MAX_LATITUDE']])
  
  wrf <- wrf_load(
    modelName = input$model,
    modelRun = strftime(input$date, "%Y%m%d00"),
    modelRunHour = modelRunHour,
    varNames = varNames,
    res = res, 
    xlim = xlim, 
    ylim = ylim
  )
  
  return(wrf)
  
})



observeEvent({ input$load }, {
  
    updateSelectizeInput(
    session,
    "index",
    choices = tryCatch(
      expr = 1:dim(bs()[[1]])[3], 
      error = function(err) { "Error." }
    )
  )
  
})

observeEvent({ input$fwd }, {
  
  updateSelectizeInput(
    session,
    "index",
    selected = ifelse(index() < dim(bs()[[1]])[3], index() + 1, index())
  )
  
})

observeEvent({ input$prv }, {
  
  updateSelectizeInput(
    session,
    "index",
    selected = ifelse(index() > 1, index() - 1, index())
  )
  
})

output$loadLink <- renderUI({
  
  req(input$model)
  
  actionButton(
    inputId = "load",
    label = tags$h4(paste("Load", input$model))
  ) 
  
})

output$plot <- renderPlot({
  
  req(meta(), bs(), wrf(), index())
  
  p <- Progress$new()
  p$set(message = "Loading Plot...")
  on.exit(p$close())
  
  meta <- meta()
  bs_raster <- bs()[[1]]
  wrf_raster <- wrf()
  
  xlim <- c(meta[['MIN_LONGITUDE']], meta[['MAX_LONGITUDE']])
  ylim <- c(meta[['MIN_LATITUDE']], meta[['MAX_LATITUDE']])
  
  states <- MazamaSpatialUtils::getState(xlim[1], ylim[1])
  
  g <- plot_base(
    xlim = xlim, 
    ylim = ylim, 
    ratio = 1.4
  ) + 
  (if ( "Scalar Field" %in% options() ) {
    layer_raster(
      raster = bs_raster[[index()]], 
      breaks = c(0, 1, 2, 5, 10, 25, 50, 100, Inf)
    ) 
  }) + 
  (if ( "County Boundaries" %in% options() ) {
    layer_counties(
      fill = "transparent", 
      xlim = xlim,
      ylim = ylim
    )
  }) + 
  (if ( "State Boundaries" %in% options() ) { 
    layer_states(
      xlim = xlim, 
      ylim = ylim
    )
  }) + 
  (if ( "Vector Field" %in% options() ) { 
    layer_vectorField(
      raster = wrf_raster, 
      uName = "U10", 
      vName = "V10"
    )
  }) + 
  ggplot2::scale_fill_brewer(
    palette = "Greys",
    na.value = "transparent"
  ) + 
  ggplot2::ggtitle(raster_getTime(bs_raster)[[index()]]) + 
  ggplot2::theme_minimal()

  return(g)

})

coords <- eventReactive({ input$plot_click }, {
  
  return(list("lng" = input$plot_click$x, "lat" = input$plot_click$y))
  
})

output$subplot <- renderPlot({
  
  req(bs(), coords())
  
  p <- Progress$new()
  p$set(message = "Loading Location Plot...")
  on.exit(p$close())
  
  raster_spaghettiPlot(bs(), coords()$lng, coords()$lat) + 
  ggplot2::theme_minimal()
  
})

```


